DROP TABLE IF EXISTS Cruise CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Ship CASCADE;
DROP TABLE IF EXISTS Technician CASCADE;
DROP TABLE IF EXISTS Captain CASCADE;
DROP TABLE IF EXISTS Crew CASCADE;
DROP TABLE IF EXISTS Reservation CASCADE;
DROP TABLE IF EXISTS Waitlist;
DROP TABLE IF EXISTS Confirmed;
DROP TABLE IF EXISTS Reserved;
DROP TABLE IF EXISTS Schedule;
DROP TABLE IF EXISTS repairs;
DROP TABLE IF EXISTS CruiseCustomer; 
DROP TABLE IF EXISTS CruiseReservation;
DROP TABLE IF EXISTS CruiseCaptain; 
DROP TABLE IF EXISTS CruiseShip;
DROP TABLE IF EXISTS request;


CREATE TABLE Cruise (c_num INTEGER, cost INTEGER, num_sold INTEGER, num_stops INTEGER, actual_arrive_date DATE, actual_depart_date DATE, actual_depart_time TIME, source CHAR(20), destination CHAR(20), PRIMARY KEY (c_num));

CREATE TABLE Customer (first_name CHAR(20), last_name CHAR(20), gender CHAR(10), date_of_birth DATE, address CHAR(40), contact_num INTEGER, ID INTEGER, ZIP_code INTEGER, PRIMARY KEY (ID));

CREATE TABLE Ship (model CHAR(20), ID1 INTEGER, make CHAR(20), age INTEGER, Seats Integer, PRIMARY KEY(ID1));

CREATE TABLE Technician (ID2 INTEGER, PRIMARY KEY (ID2));

CREATE TABLE Captain (ID Integer, name CHAR(20), PRIMARY KEY (ID));

CREATE TABLE Crew (name CHAR(20), ID INTEGER, PRIMARY KEY (ID));

CREATE TABLE Reservation (Rnum INTEGER, ID INTEGER, PRIMARY KEY (Rnum), FOREIGN KEY (ID) REFERENCES Customer);
CREATE TABLE Waitlist (Rnum INTEGER, PRIMARY KEY (Rnum), FOREIGN KEY (Rnum) REFERENCES Reservation);
CREATE TABLE Confirmed (Rnum INTEGER, PRIMARY KEY (Rnum), FOREIGN KEY (Rnum) REFERENCES Reservation);
CREATE TABLE Reserved (Rnum INTEGER, PRIMARY KEY (Rnum), FOREIGN KEY (Rnum) REFERENCES Reservation);

CREATE TABLE Schedule (day DATE, depart_time TIME, arrive_time TIME, c_num INTEGER, PRIMARY KEY (c_num), FOREIGN KEY (c_num) REFERENCES Cruise ON DELETE CASCADE);

CREATE TABLE repairs (date DATE, code INTEGER, ID1 INTEGER, ID2 INTEGER, PRIMARY KEY(ID1, ID2), FOREIGN KEY (ID1) REFERENCES Ship, FOREIGN KEY (ID2) REFERENCES Technician);

CREATE TABLE CruiseCustomer (c_num INTEGER, ID INTEGER, PRIMARY KEY (c_num, ID), FOREIGN KEY (c_num) REFERENCES Cruise, FOREIGN KEY (ID) REFERENCES Customer);

CREATE TABLE CruiseReservation (c_num INTEGER, Rnum INTEGER, PRIMARY KEY (c_num, Rnum), FOREIGN KEY (c_num) REFERENCES Cruise, FOREIGN KEY (Rnum) REFERENCES Reservation);

CREATE TABLE CruiseCaptain (c_num INTEGER, ID INTEGER, PRIMARY KEY (ID), FOREIGN KEY (c_num) REFERENCES Cruise, FOREIGN KEY (ID) REFERENCES Captain);

CREATE TABLE CruiseShip (c_num INTEGER, ID INTEGER, PRIMARY KEY (ID), FOREIGN KEY (c_num) REFERENCES Cruise, FOREIGN KEY (ID) REFERENCES Ship);

CREATE TABLE request (ID INTEGER, RID INTEGER, ID1 INTEGER, ID2 INTEGER, PRIMARY KEY (ID, ID1, ID2), FOREIGN KEY (ID) REFERENCES Captain, FOREIGN KEY (ID1) REFERENCES Ship, FOREIGN KEY (ID2) REFERENCES Technician);

